version: "3.9"
services:
  app:
    build: .
    image: mipt-terrain-clustering:latest
    ports:
      - "8501:8501"
    environment:
      - MPLBACKEND=Agg
    volumes:
      - ./:/app
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501


